### ISSUE TITLE
Add contributing rules

### ISSUE THREAD

**Issue by rossanodan** [EddieJaoudeCommunity/EddieBotUI#1]
The project needs clear contributing rules so that people can follow them contributing to the codebase.
Is there any template we can customise and use?

**Comment by rossanodan** [comment]
I found this template https://gist.github.com/PurpleBooth/b24679402957c63ec426
It's limited but a good starting point 👀

**Comment by eddiejaoude** [comment]
Cool 👍 . I know @PurpleBooth too! So I am happy to use and contribute back 🤓

**Comment by rossanodan** [comment]
ATM I'm browsing her repos 😆

**Comment by rossanodan** [comment]
@eddiejaoude I will take inspiration from here https://github.com/PurpleBooth/a-good-readme-template 💯

**Comment by eddiejaoude** [comment]
Cool 👍
