### ISSUE TITLE
Do we like Bootstrap?

### ISSUE THREAD

**Issue by rossanodan** [EddieJaoudeCommunity/EddieBotUI#12]
Question: do we like Bootstrap for this app? It could be helpful for layouts, responsiveness, default styles (links, menus, buttons, etc) and for the normalization of the CSS.

What do you think? @eddiejaoude @BOLT04 and others

**Comment by eddiejaoude** [comment]
I like using Bootstrap or Material - it helps get things moving fast, I appreciate it also has limitations. But the kick starting the project I think out weight the limitation

**Comment by BOLT04** [comment]
I'm not against using Bootstrap either, but maybe we could decide on using just one CSS framework? We added [Semantic UI](https://semantic-ui.com/) and [Semantic UI React](https://react.semantic-ui.com/) for helpful React components, but maybe we could remove them if we add Bootstrap instead.

My concern is overlapping styles from both frameworks, but do you guys think there are other issues, or any issues, in using two frameworks?

**Comment by rossanodan** [comment]
Thanks for your opinion @eddiejaoude and @BOLT04.
What we can do is evaluate it: I will create a branch and I will setup Bootstrap (not react-bootstrap). Then we can decide if we want to keep it. I don't like using CSS frameworks, to be honest. But for small projects it's fine. Bootstrap is very consistent. I also have to take a look at https://tailwindcss.com/

Keep you posted 💪

**Comment by eddiejaoude** [comment]
Cool, keep us posted @rossanodan . I agree with @BOLT04 we should not try to use more than one, I think focusing on a single solution would make more sense

**Comment by Buezor** [comment]
I think Bootstrap is nice, although is has some limitations it is still good for creating responsive web pages. So its a yes from me.

**Comment by rossanodan** [comment]
We decided to proceed with [Tailwind CSS](https://tailwindcss.com/).
