### ISSUE TITLE
Spelling Error in Readme

### ISSUE THREAD

**Issue by AllanRegush** [EddieJaoudeCommunity/EddieBotUI#18]
There is a spelling error in the Readme

## Summary

- [Getting Started](#getting-started)
- [Runing the tests](#running-the-tests)
- [Deployment](#deployment)

Should be: 

## Summary

- [Getting Started](#getting-started)
- [Running the tests](#running-the-tests)
- [Deployment](#deployment)

**Comment by eddiejaoude** [comment]
thanks @AllanRegush 👍 . I added the label `bug` and `good first issue` to it

**Comment by Victorybrown** [comment]
is this taken?
looks like a good first issue i can work on

**Comment by eddiejaoude** [comment]
@tory-brown go for it 👍 - I have assigned it to you 🤓

**Comment by eddiejaoude** [comment]
Oh wait, I think it has been fixed already 🤦‍♂️ - sorry

I am sure there are many more spelling mistakes. Someone spelt my name wrong, that still needs fixing, let me try to find it

**Comment by eddiejaoude** [comment]
I found it @tory-brown , let me raise a new Issue and close this one. I will assign the new one to you

**Comment by eddiejaoude** [comment]
@tory-brown I assigned a ticket to you https://github.com/EddieJaoudeCommunity/support/issues/136 any questions let us know in ticket #136
