### ISSUE TITLE
Hello Eddie, wanted to part of this community

### ISSUE THREAD

**Issue by NirmalSilwal** [EddieJaoudeCommunity/EddieBotUI#22]
Hello there! first test issue in this community!

![Screenshot (155)](https://user-images.githubusercontent.com/31946761/93223569-d4bfa400-f78d-11ea-8b1b-736d652292c4.png)

**Comment by NirmalSilwal** [comment]
happy Engineers Day - ❤️ from Nepal

![happy engineers day](https://user-images.githubusercontent.com/31946761/93224210-8068f400-f78e-11ea-9ec4-1edec9e55f3f.PNG)

Yay!

**Comment by BOLT04** [comment]
Hey @NirmalSilwal 😃, if you want to join the community open an issue in the support repo and add the "invite me to the organization" label. We have a FAQ for that question [here](https://github.com/EddieJaoudeCommunity/support#faq) 👍.

I'm glad you want to be a part of the community and contribute to open source. If you want to contribute with a new repository idea and a different stack, or add features to existing repos, we are more than welcome to help you do it 😃.

**Comment by NirmalSilwal** [comment]
Hi @BOLT04 thank you for the clarification.

I am more than happy to be the  part of this organization. Looking forward to contribute.

**Comment by eddiejaoude** [comment]
@NirmalSilwal great screenshot 👍 .

Thanks @BOLT04 👍 

@NirmalSilwal I see you are part of our community Github organisation now - if you have any issues let me know 🤓

**Comment by NirmalSilwal** [comment]
yeah, thank you @eddiejaoude for having me in the organization 👍
