### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by RemcoHalman** [EddieJaoudeCommunity/EddieBotUI#25]
Forked the project. And running the setup the way README describes. When running `npm install` i get the following error. What can i do to proceed with the install? 

```
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
```

**Comment by RemcoHalman** [comment]
Ok typescript was not installed. Solved by running `npm install typescript` and rerunning `npm install`

**Comment by BOLT04** [comment]
Hi @RemcoHalman, thank you for raising this issue 😃. 
Your question is completely valid and I think we can improve the documentation on the README to include that TypeScript needs to be installed. If you want you can raise a PR with something like this:


### Prerequisites
-  Typescript
   TypeScript is a dependency of `<the package name>` , so you need to install it first.

   ```bash
   npm install typescript
   ```

**Comment by RemcoHalman** [comment]
@BOLT04  Thanks for the tip! Added to the README and made a pull request. As a bonus added a little styling

**Comment by eddiejaoude** [comment]
Looks likes `typescript` is missing from the project, we need to add it to `package.json` in the `devDependencies` - I think this project needs a reboot though
