### ISSUE TITLE
Update CONTRIBUTING.md with useful and clear information

### ISSUE THREAD

**Issue by rossanodan** [EddieJaoudeCommunity/EddieBotUI#32]
**Is your feature request related to a problem? Please describe.**
The CONTRIBUTING.md file is empty at the moment. It should contains information and guides to get started with the codebase of EddieBotUI.

**Sections**
1. Structure of the codebase
    - components
    - services
    - ...
2. Coding rules
3. How to contribute
   - Create an issue/feat branch
   - Commit changes
   - Create the pull request
   - Add labels to the pull request

**Questions**
1. Are there any CONTRIBUTING.md models to take inspiration from?

**Comment by eddiejaoude** [comment]
Regarding `CONTRIBUTING.md` I was thinking to create a new repo that has all our docs, that also syncs to each of our projects on a GitHub Action.

**Comment by rossanodan** [comment]
> Regarding `CONTRIBUTING.md` I was thinking to create a new repo that has all our docs, that also syncs to each of our projects on a GitHub Action.

Great idea @eddiejaoude, let me know how you want to proceed 😄

**Comment by eddiejaoude** [comment]
I think we have 2 options here:

1. park this for the moment
2. create the file and add contents now, later they can be combined together and centralised 

Up to you which you prefer

**Comment by BOLT04** [comment]
I support the creation of an action and a centralized file for `CONTRIBUTING.md` 👍. The sections like "Structure of the codebase" would be on each codebase, since they are different, or moved to README. Commit messages, PRs, labels, feature branches... all that can be the same, and it's pretty cool to move in this direction 😃

**Comment by rossanodan** [comment]
> I think we have 2 options here:
> 
> 1. park this for the moment
> 2. create the file and add contents now, later they can be combined together and centralised
> 
> Up to you which you prefer

I think I'm going to create some content now and then, as you said, we can move it elsewhere. @BOLT04 we can also move it to the README when we'll have the repository for contributing rules. I mean, specific instructions can be moved to the README file.
