### ISSUE TITLE
Under maintenance and coming soon mode

### ISSUE THREAD

**Issue by rossanodan** [EddieJaoudeCommunity/EddieBotUI#33]
**Is your feature request related to a problem? Please describe.**
It would be great having the `Under Maintenance` and the `Coming Soon` mode, especially now that the application is not ready to be displayed yet.

**Describe the solution you'd like**
Using environment variables we can toggle on/off the two application states, giving a proper priority. Let me explain with an example.

## Scenario 1
```
REACT_APP_UNDER_MAINTENANCE=false
REACT_APP_COMING_SOON=false
```
The application works normally, without any particular difference.

## Scenario 2
```
REACT_APP_UNDER_MAINTENANCE=true
REACT_APP_COMING_SOON=false
```
The application shows only the under maintenance view, preventing the user to display any other part of the application. This state should be used only when massive changes are coming that risk to break the functionality.

## Scenario 3
```
REACT_APP_UNDER_MAINTENANCE=false
REACT_APP_COMING_SOON=true
```
The application shows only the coming soon view, preventing the user to display any other part of the application. This state should be used only when parts of the application are not ready yet to be shown.

## Scenario 4
```
REACT_APP_UNDER_MAINTENANCE=true
REACT_APP_COMING_SOON=true
```
The application shows only the under maintenance view, preventing the user to display any other part of the application. The under maintenance state has more priority.

These environment variables can be easily used in the application router.

**Comment by eddiejaoude** [comment]
Good idea. Some thoughts...

- Deploys will be fast, so not sure about under maintenance, but the coming soon holding page would be good now
- Would coming soon always be needed, because once we get the first page up, there will always be something to show?

**Comment by rossanodan** [comment]
> Good idea. Some thoughts...
> 
> * Deploys will be fast, so not sure about under maintenance, but the coming soon holding page would be good now
> * Would coming soon always be needed, because once we get the first page up, there will always be something to show?

Agree about the under maintenance, pointless. The coming soon mode will be used only now, in the bootstrapping phase of the project. It's a placeholder until we'll have something to show.

**Comment by rossanodan** [comment]
Worked on this issue in https://github.com/EddieJaoudeCommunity/EddieBotUI/pull/34
