### ISSUE TITLE
fix: README.md mentions our Discord server's previous name.

### ISSUE THREAD

**Issue by shreemaan-abhishek** [EddieJaoudeCommunity/EddieBotUI#46]
![this](https://user-images.githubusercontent.com/61597896/130367958-9fab5e10-8492-4638-8a01-baec00acfec2.png)

**Comment by ANURAG-PATHAK** [comment]
hey can I work on this issue, I am new I will be needing some guidance, thank you

**Comment by shreemaan-abhishek** [comment]
Sure! Go for it.
We actively welcome your pull requests.

- Fork the repo and create your branch from develop.
- Make changes in the Readme.md
- Commit your changes
- Push your changes to the forked repository
- Then open a pull request

**Comment by ANURAG-PATHAK** [comment]
hey @shreemaan-abhishek can you give me the link of the discord please

**Comment by suhail34** [comment]
Is the issue open now ? would like fix this issue

**Comment by ANURAG-PATHAK** [comment]
> Is the issue open now ? would like fix this issue

I already pulled a PR so the issue is fixed in #47 
thank you for your contribution and concern

**Comment by suhail34** [comment]
Okay Thanks 😄
