### ISSUE TITLE
Refactor suggestions

### ISSUE THREAD

**Issue by BOLT04** [EddieJaoudeCommunity/EddieBotUI#5]
- We can use a [React Fragment](https://reactjs.org/docs/fragments.html) [here](https://github.com/EddieJaoudeCommunity/EddieBotUI/blob/develop/src/App.js#L10) instead of a `div`, like this
```jsx
<>
<Switch>...</Switch>
</>
```
- The file `App.css` is empty. Since we are using SCSS we could delete this and remove [this import](https://github.com/EddieJaoudeCommunity/EddieBotUI/blob/develop/src/App.js#L4)
- The `App` component doesn't use any state, so maybe we could simply use a functional component here.

What do you think @rossanodan?

**Comment by rossanodan** [comment]
@BOLT04 `App.scss` exists now and we can use it for global styles like font-family. The `React.Fragment` is a good idea, I'll fix it 👍
